CREATE DATABASE [Hospital]
GO
USE [Hospital]
GO

CREATE TABLE [Departments] (
	[Id] INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL CHECK(LEN(Name) > 0) UNIQUE
);

CREATE TABLE [Doctors] (
	[Id] INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(MAX) NOT NULL CHECK(LEN(Name) > 0),
	[Premium] MONEY NOT NULL CHECK([Premium] > 0) DEFAULT 0,
	[Salary] MONEY NOT NULL CHECK([Salary] > 0),
	[Surname] NVARCHAR(MAX) NOT NULL CHECK(LEN([Surname]) > 0)
);

CREATE TABLE [Specializations] (
	[Id] INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL CHECK(LEN(Name) > 0) UNIQUE
);

CREATE TABLE [Sponsors] (
	[Id] INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(MAX) NOT NULL CHECK(LEN(Name) > 0)
);

CREATE TABLE [DoctorsSpecializations] (
	[Id] INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
	[DoctorId] INT NOT NULL FOREIGN KEY REFERENCES [Doctors](Id),
	[SpecializationId] INT NOT NULL FOREIGN KEY REFERENCES [Specializations](Id)
);

CREATE TABLE [Donations] (
	[Id] INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
	[Amount] MONEY NOT NULL CHECK ([Amount] > 0),
	[Date] DATE NOT NULL CHECK ([Date] <= GETDATE()) DEFAULT GETDATE(),
	[DepartmentId] INT  NOT NULL FOREIGN KEY REFERENCES [Departments](Id),
	[SponsorId] INT NOT NULL FOREIGN KEY REFERENCES [Sponsors](Id)
);

CREATE TABLE [Vacations] (
	[Id] INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
	[StartDate] DATE NOT NULL,
	[EndDate] DATE NOT NULL,
	[DoctorId] INT NOT NULL FOREIGN KEY REFERENCES [Doctors](Id),
	CONSTRAINT vacation_check CHECK ([EndDate] > [StartDate])
);

CREATE TABLE [Wards] (
	[Id] INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(20) NOT NULL CHECK(LEN(Name) > 0) UNIQUE,
	[DepartmentId] INT NOT NULL FOREIGN KEY REFERENCES [Departments](Id)
);

